### ISSUE TITLE
Vue Dev doesnt shows  array correct

### ISSUE THREAD

**Issue by patpaskoch** [vuejs/vue-devtools#121]
I created a computed array with dates from one week.

Vue Dev  shows me 
weekDays: Array[7] computed
0: "2016-06-26T22:00:00.000Z"
1: "2016-06-27T22:00:00.000Z"
2: "2016-06-28T22:00:00.000Z"
3: "2016-06-29T22:00:00.000Z"
4: "2016-06-30T22:00:00.000Z"
5: "2016-07-01T22:00:00.000Z"
6: "2016-07-02T22:00:00.000Z"

but if I console.log the array it shows me:
[
Mon Jun 27 2016 00:00:00 GMT+0200 (CEST), 
Tue Jun 28 2016 00:00:00 GMT+0200 (CEST), 
Wed Jun 29 2016 00:00:00 GMT+0200 (CEST), 
Thu Jun 30 2016 00:00:00 GMT+0200 (CEST), 
Fri Jul 01 2016 00:00:00 GMT+0200 (CEST), 
Sat Jul 02 2016 00:00:00 GMT+0200 (CEST), 
Sun Jul 03 2016 00:00:00 GMT+0200 (CEST)
]

the console.log is correct, vue is also working with the correct array, just vue dev shows the that array with a shift.

**Comment by LinusBorg** [comment]
Can your provide sample code what exactly that arraxy contains etc? were those date objects?

Because this seems to be a simple formatting question between local time and UTC. both dev tools and your console output show the same datetimes - it's just that in devtools they appear as UTC, while in the console they appear as local time.

**Comment by yyx990803** [comment]
This is because Date objects are not serialized by circular-json-es6. Preferrably you should only use JSON-serializable values as your data.

**Comment by patpaskoch** [comment]
thx for the fast reply, that worked me, btw I love vue, so much fun to program
