### ISSUE TITLE
Nested slots and wrong hierarchy

### ISSUE THREAD

**Issue by jakobhenner** [vuejs/vue-devtools#122]
First of all: Damn, Vue made it fun to code again!

I have a _Column_ component:

``` html
<template>
  <div class="column" :class="classes">
    <slot></slot>
  </div>
</template>
```

A _Row_:

``` html
<template>
  <div class="row" :class="classes">
    <slot></slot>
  </div>
</template>
```

A _Container_:

``` html
<template>
  <div class="container" :class="classes">
    <slot></slot>
  </div>
</template>
```

And finally a _Layout_ component:

``` html
<template>
  <div class="layout">
    <container inner>
      <row align-items="center">
        <column type="text">
          <slot name="text"></slot>
        </column>
        <column type="image" gutterless>
          <slot name="image"></slot>
        </column>
      </row>
    </container>
  </div>
</template>
```

Then used:

``` html
<layout>
  <text slot="text">Hello there</text>
  <hero-image slot="image"></hero-image>
</layout>
```

The DOM output is as expected:

```
- Layout
   - Container
      - Row
         - Column
            - [content]
         - Column
            - [content]
```

However, The Vue devtools shows the hierarchy wrong:

```
- Layout
   - Container
      - Row
         - Column
         - Column
   - [content] 
   - [content] 
```

I guess it's all the nested slots. I've ensured that all elements are closed properly - and again there's nothing wrong with the DOM output. 

Just a minor thing that nags me!

**Comment by LinusBorg** [comment]
I think this is intentional. At least it depends on what the component tree in devtools is *supposed* to show:

* should it show the the `$parent` tree, which will be similar to the resulting DOM tree, or
* should it show the context in which child component is evaluated

Currently, it behaves like the second option. As your can see,  in your example, the `text-slot` and `hero` components are evaluated in the context of the `layout` component.

This information would be lost when your place it in the end position according to the $parent tree / DOM tree.
