### ISSUE TITLE
component tree not supported

### ISSUE THREAD

**Issue by RakshithNM** [vuejs/vue-devtools#1235]
### Version
6.0.0-beta.1

### Browser and OS info
chrome(Version 84.0.4147.89 (Official Build) (64-bit)) and mac os x(10.15.4 (19E287))

### Steps to reproduce
Open up vue dev tools, a tooltip with "component tree not supported" error comes up. Also the console says "App with id null not found"

### What is expected?
i should be able to inspect and check my vue components

### What is actually happening?
i am unable to see the components on the page

---
Now i need to check how to get the earlier version of vue devtools on chrome

**Comment by pydlv** [comment]
I'm getting the same thing. I'm running Vue 2.6.11. Any way to downgrade the extension version? For some reason it put me on the new beta.

**Comment by albertorsesc** [comment]
Same issue, since a few minutes ago.

**Comment by devdnn** [comment]
Same issue, Firefox is working so using it till this gets fixed. Firefox addon was not updated like Chrome extension.

**Comment by zhouxinyong** [comment]
Same issue.

**Comment by jondavidpass** [comment]
Also experiencing this since today.

**Comment by devdnn** [comment]
Just read the Overview for the chrome extension here in this [link](https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg)

**_- Currently only supports Vue 3
- Only provides component inspection for now - other features coming soon._**

We are out of cookie till they fix the issues :(

**Comment by ThePpeecc** [comment]
It turned out that I had installed the wrong plugin as there looked to be two different versions. 

The one I had installed was 6.0.0 beta 1 from [here ]( https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg) 
Whereas the right one to use if working with Vue 2.6 can be found [here](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)

**Comment by fremdev** [comment]
ThePpeecc is right. I've been using beta by default long time - and now it doesn't work with Vue 2.x, but the usual not beta version from the [store](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd) is working fine

**Comment by ZhuZean** [comment]
Same issue from yesterday.

**Comment by Sandra-Kao** [comment]
The same issue here from 07/20

**Comment by Akryum** [comment]
Please use the [stable version](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd) for Vue 2.x

**Comment by leopiccionia** [comment]
It seems that, because I installed 5.0-beta back in the day, I was in the beta channel for the extension or something, so I received an auto-upgrade to 6.0-beta.

Installing the [stable extension](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd) does fix the issue.
