### ISSUE TITLE
Distinguishing multiple apps

### ISSUE THREAD

**Issue by p3k** [vuejs/vue-devtools#1405]
### Version
6.0.0-beta.7

### Browser and OS info
Chrome 89 / Ubuntu 18.04

### Steps to reproduce
1. Integrate more than one Vue app in a website
2. Open Vue dev tools
3. Click the application drop down

### What is expected?
A list of application names easily to be distinguished is displayed (e.g. Header, Footer, Tooltip).

### What is actually happening?
A list of similar application names is displayed (e.g. App 1, App 2,  App 3)

---
Here is a screenshot: https://pasteboard.co/JXpLdoH.png

**Comment by Akryum** [comment]
I guess you didn't put names on your root component, so the devtools can't guess them?

**Comment by p3k** [comment]
i am aware this might go beyond the focus of this repo, but could you please elaborate how to put a name on the root component?

this is basically the way we mount the apps:

```js
import { createApp } from "vue";
import App from "./app.vue";
createApp(App).mount("#app");
```

**Comment by Akryum** [comment]
Open your `app.vue` file and put `export default { name: 'My app' }` ([docs](https://v3.vuejs.org/api/options-misc.html#name)).

**Comment by p3k** [comment]
thanks a lot, i really was looking for this – maybe need new glasses :wink:

**Comment by lighth7015** [comment]
Doing this only changes the app's element tag name; e.g.
```js
import Vue from 'vue';
Vue.$mount({ name: 'FooBar' });
```
gives me a `FooBar` root element, e.g.-
```xml
<FooBar>
   ...
</FooBar>
```
leaving the Application name/ID as `App 1`.

**Comment by zealot128** [comment]
**I've found a workaround, at least with Vue2**

You will have to set the ``name`` property on the Vue root/app instance **afterwards**:

```javascript
const app = new Vue({..., name: "This-Sets-Only-The-Root-Name"})
app.name = "This-changes-the-app-name-in-app-dropdown"
```

Passing the name property to the constructor only changes the name of the "Root" component, which changes nothing about the App-Selector.

But now, we can at least add the root-component name to the app-select dropdown:

<img width="383" alt="Bildschirmfoto 2021-11-29 um 10 41 06" src="https://user-images.githubusercontent.com/147175/143844458-3981245c-c767-48c3-bb33-ad0060286071.png">

...instead of the previous anonymous dropdown list:

<img width="397" alt="Bildschirmfoto 2021-11-29 um 10 29 39" src="https://user-images.githubusercontent.com/147175/143844546-fa047ac7-02fb-4168-abd2-f6aa0ecf943c.png">


This is/was a real issue after upgrading to newer Vue Tools. I really really liked the old way, where all Root were shown in the component finder window:

```
<Root>
   <ComponentA>
<Root>
  <Componet B>
..
```

But the workaround works for us now.

**Comment by Akryum** [comment]
@zealot128 It's not a workaround, it's how it's supposed to work. The selector takes the name of the root components.

> I really really liked the old way, where all Root were shown in the component finder window

This caused a lot of issues such as preventing supporting multiple vuex stores/routers on the same page, and wouldn't work with the timeline.

**Comment by p3k** [comment]
@zealot128 this is a nice way to define a name dynamically – but in fact it does not work with vue3:

```
const app = createApp(component, props);
app.name = name;
app.mount(selector);
```

i am still seeing the name as defined in the sfc via the `name` property… (see https://github.com/vuejs/devtools/issues/1405#issuecomment-820260108)

is there a way to do this in vue3, so i can assign different names for one and the same component used multiple times in the dom?

**Comment by Akryum** [comment]
```js
const app = createApp({ ...component, name: 'foo' }, props)
```

**Comment by p3k** [comment]
ah of course! perfect, thanks @Akryum

**Comment by zealot128** [comment]
> @zealot128 It's not a workaround, it's how it's supposed to work. The selector takes the name of the root components.
> 
> > I really really liked the old way, where all Root were shown in the component finder window
> 
> This caused a lot of issues such as preventing supporting multiple vuex stores/routers on the same page, and wouldn't work with the timeline.

I guessed so after reading ``packages/app-backend-api/src/api.ts``, that's why I've tried this approach.

Only the typings of Vue do not allow a "name" here, so it is not obvious that a "name" can be applied here:

![Bildschirmfoto 2021-11-29 um 13 24 08](https://user-images.githubusercontent.com/147175/143867622-77dbbaaa-a557-4959-b35b-c883a93e4aed.png)

Nevertheless, it now works good with the name property! Future Googler's can find this post. 

Or maybe it is possible to add a hint in the box if one has more than one "App" on the bottom of the mouse wheel hint? Like a link to this issue or a modal with explanation of adding the name property to a Vue instance to change the name, maybe.

<img width="283" alt="Bildschirmfoto 2021-11-29 um 13 25 41" src="https://user-images.githubusercontent.com/147175/143867884-6bcc4956-a1f7-4d03-a585-dfeee85bdcf5.png">

**Comment by Akryum** [comment]
> Only the typings of Vue do not allow a "name" here, so it is not obvious that a "name" can be applied here:

You need to put it in the options of the root component.

**Comment by Akryum** [comment]
Hmm looks like an issue then

**Comment by Akryum** [comment]
So the intended way is to put a `name` in the options of the root component and will be fixed in the next release.

**Comment by zealot128** [comment]
@Akryum perfect! Thank you for the quick fix!

**Comment by jackchoumine** [comment]
> Hmm looks like an issue then

Vue3 project has this issue as well.

**Comment by jackchoumine** [comment]
> @Akryum perfect! Thank you for the quick fix!

vue3 project has this issue too,

![image](https://github.com/vuejs/devtools/assets/21340150/73f66651-1dae-47ca-8e50-c9d19ad3ace3)
