### ISSUE TITLE
Vue 3 app.unmount() causes several exceptions to be thrown after 2 seconds - Timed out getting app record for app [object Object]

### ISSUE THREAD

**Issue by deot** [vuejs/vue-devtools#1480]
### Version
6.0.0-beta.14

### Browser and OS info
Chrome 91 / Mac 11.2.1

### Steps to reproduce
main.ts

```ts
import { createApp } from "vue";
import App from "./App.vue";

const vm = createApp(App);
vm.mount("#app");
vm.unmount();
```

### What is expected?
no error.

### What is actually happening?
```
Uncaught (in promise) Error: Timed out getting app record for app [object Object]
    at backend.js:811
```
##### Screenshot
![2021-06-10 at 09 43 38](https://user-images.githubusercontent.com/18424466/121451591-777d1a00-c9d0-11eb-894f-6816d3030693.png)
![09 48 13](https://user-images.githubusercontent.com/18424466/121451939-1ace2f00-c9d1-11eb-837f-9c608015442f.png)

**Comment by redfox05** [comment]
I can confirm I also get this error. Glad it's not just me or my code.
The error is from backend.js and goes away if I disable the vue devtools extension, so we know its the devtools plugin, not one generated by the vue application.

Browser: Chrome Version 91.0.4472.101 (Official Build) (x86_64)
Vue devtools version: 6.0.0 beta 14
Vue: 3.0.4

**Comment by cloud-mouse** [comment]
Is there a solution for this? I also encountered the same problem.

**Comment by redfox05** [comment]
I tried everything from wondering if it was listeners that had not been removed before unmounting etc, but nothing changes. For now I'm just trying to ignore the errors, but theres so many that fly up, it really affects development.

Would be nice if this issue could at least be acknowledged.

@deot Can you add the actually exception error message into the title, so that more people can come across this thread if they are searching for it via search engines? I only found this by manually checking the vue devtools issue page, and some people might not even realise its related to the vue chrome extension.

Suggestion for title:
> Vue 3 app.unmount() causes several exceptions to be thrown after 2 seconds - Timed out getting app record for app [object Object]

**Comment by zhch-hong** [comment]
chrome vue-devtools extension, disabled

**Comment by redfox05** [comment]
Fantasic! That was quick @Akryum thanks!

Question though, looking at the PR, it seems mainly to remove errors on production builds with the try/catches, but doesn't seem to change much for non-production? Unless I missed something? I'll look forward to updating and trying anyway.
