### ISSUE TITLE
Weird behaviour when traveling to a mutation using a select without default option selected

### ISSUE THREAD

**Issue by gaspoute** [vuejs/vue-devtools#224]
Hello,

I observed a weird behaviour when trying to travel to a mutation using a select without an option selected by default.

I created a [repository](https://github.com/gaspoute/vue-devtools-select) to show you how to reproduce the bug.

When we load the items of the ```select```, we select the first item and we try to travel to the mutation that loads the items, several mutations are committed instead putting the mutation that loads the items active.

PS: sorry for my poor English :-)

Gaspar.

**Comment by posva** [comment]
I'd say this is normal because there's no possible value for `null` when the `selectedItemId` is equal to `null` and therefore the `v-model` directive triggers a `change` event which is caught on your application to commit a mutation which appears.
As you pointed out, the best solution is to include an empty option:

```html
    <option disabled :value="null"></option>
```
the value is the same as set by default in the state
