### ISSUE TITLE
Add support for Opera browser

### ISSUE THREAD

**Issue by coderdiaz** [vuejs/vue-devtools#241]
Add-in not available in Opera Store

**Comment by coderdiaz** [comment]
Solved.

I was download the latest version of the add-in from the Chrome Store and set up with the **dev mode** in Opera.
Now it works :) 

**Browser**: Opera 42.0.2393.137
Only need to publish the add-in to Opera Store.

Greetings

**Comment by posva** [comment]
Having to keep updated one page instead of two for the plugin is better imo. Since the plugin can be installed in Opera and browsed using something like https://addons.opera.com/en/extensions/details/download-chrome-extension-9/

**Comment by coderdiaz** [comment]
Thanks @posva 👍

**Comment by posva** [comment]
Thank you for the hint. Didn't know chrome extensions could be directly used in Opera 🙂

**Comment by coderdiaz** [comment]
I didn't know either xD

**Comment by cpxPratik** [comment]
@posva , That opera extension doesn't work. Simply says 'Unable to download extension package' on any chrome extension i tried, including vuejs. If the same code without any change can be used, then why not publish it? It wastes time finding out about how to work on opera, through a closed issue, while simply publishing it would work. Or at least mention it's same on opera and we have to manually install on readme.md. Now i have to find out how to get crx file for vuetool and install it manually on opera, so instead of wasting time even further, i will stay on chrome.

**Comment by abuuzayr** [comment]
Thanks @coderdiaz! This was helpful for me.

**Comment by gangsthub** [comment]
> using something like [addons.opera.com/en/extensions/details/download-chrome-extension-9](https://addons.opera.com/en/extensions/details/download-chrome-extension-9/)

Nowadays, it's not even needed. You can just install it from the Chrome Web Store:

https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd

Hint: reload the vue page and close+open devtools to see it ;)

![image](https://user-images.githubusercontent.com/6775220/73718201-285c1080-471c-11ea-96ff-ca667a8065ca.png)

**Comment by abuuzayr** [comment]
Sweet @gangsthub ! Thank you for sharing.
