### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by vintikzzz** [vuejs/vue-devtools#263]
When pointing to an element got error "Uncaught TypeError: Cannot read property 'appendChild' of null"
![2017-02-19 14 57 19](https://cloud.githubusercontent.com/assets/150981/23102100/cb7aee24-f6b3-11e6-90c8-d158bae57a13.png)

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO)?
Thanks!

**Comment by vintikzzz** [comment]
Hi! I did found the cause of such behaviour. Somehow I have replaced body element with my vue component. After fix everything works as expected. Sorry for that!

**Comment by truefusion** [comment]
I had the same issue. The solution for me was to make sure the script is loaded **after** all other scripts. "Add to the top of the page you want to debug" is partially ambiguous (since "top of page" does not necessarily describe whether it should be in the body tag or the head tag), but it is also an inaccurate instruction (at least in my case). Documentation also does not specify "inside of the body tag." In fact, bottom of the page works, too.
