### ISSUE TITLE
Component imported outside of project has no inspectable data

### ISSUE THREAD

**Issue by iliran11** [vuejs/vue-devtools#380]
**my enviroment:**

- vue": 2.3.3

- Vue.js devtools: 3.1.6

- chrome: Version 59.0.3071.115

When i am importing a `.vue` file, outside of the project folder, like this: `../../src/components/hello.vue` and trying to inspect the component, i get a message `this instance has no reactive data`.

![image](https://user-images.githubusercontent.com/24987188/28492677-23bd6402-6f10-11e7-941b-5d60f9536940.png)

after moving this file to the project folder, and referencing it with `./components/hello.vue` - i can see its `msg` property value.

the template is the default hello template that comes with [webpack template](https://github.com/vuejs-templates/webpack)

**Comment by bartlomieju** [comment]
Are you sure you are using up-to-date version? In screenshot I can see the bug that was fixed in #292. Please update devtools to newest version and let us know again

**Comment by eminos** [comment]
I'm seeing this as well.
When selecting a child component in Vue devtools, it points to <Root> or some other child component higher up. Just like in your screenshot.
In my case, it only seems to happen for https://github.com/alexsasharegan/vue-transmit
@alexsasharegan

**Comment by simplesmiler** [comment]
The issue of auto selecting root component was fixed in #292.

I was **not** able to reproduce this inspection issue with Devtools 4.1.4. Components from both inside and outside the project folder, imported with both absolute and relative paths are displayed correctly.

I'm closing this, but if the problem still exists, then please reopen with a more concrete reproduction.
