### ISSUE TITLE
Causes Firefox to not display XML tree

### ISSUE THREAD

**Issue by jmsfwk** [vuejs/vue-devtools#438]
When reading a plain XML file Firefox displays the XML tree.

When *vue-devtools* is enabled it only shows the text nodes.

**Comment by JakePicton** [comment]
Well that explains it. Been trying to figure out which one of my Firefox addons was disrupting the XML tree view.

**Comment by yyx990803** [comment]
@clarkbw would you be able to look into this or point us to someone that might know what's going on?

**Comment by clarkbw** [comment]
I’ve seen this before I think. Something about the detection breaks the XML view. @digitarald might know more about how to track this down.

**Comment by digitarald** [comment]
I am asking around, hopefully got somebody to check this tomorrow.

**Comment by rpl** [comment]
@digitarald I looks that this issue has been already fixed in #385 by checking if the document is `instanceof HTMLDocument` before injecting a tag script into the document:
 
  https://github.com/vuejs/vue-devtools/blob/472f3c67200bd70853bc5a93c401cbe9b46fc00f/shells/chrome/src/detector.js#L31-L36

I build the extension from this repo master branch and I confirm that, with the above fix, the XML viewer is rendered as expected on XML documents loaded into Firefox. 

The version of vue-devtools on AMO doesn't include this fix yet.

**Comment by prog-rajkamal** [comment]
As this issue is already fixed. any idea how soon can we expect an updated version of Vuejs devtools on AMO?

**Comment by prog-rajkamal** [comment]
It seems @yyx990803 has updated the extension. This issue can now be closed.

**Comment by yyx990803** [comment]
Lol double close!

**Comment by Akryum** [comment]
😹
