### ISSUE TITLE
Vue devtools tab doesn't retain it's position when reordering Chrome devtools tabs

### ISSUE THREAD

**Issue by LukeusMaximus** [vuejs/vue-devtools#441]
Chrome devtools remember the position they were in if they are reordered by the user (via drag-drop). The Vue tab is the exception; it is always placed on the right end of the set of tabs.

**Comment by yyx990803** [comment]
That's not the case for me - it does retain position for me. Either way, this is a Chrome issue and cannot be fixed by `vue-devtools` itself.

**Comment by posva** [comment]
My bad, it happens in version 62 as well but I thought it was a bug because other extensions **did** retain their positions but Vue is the only one (among those extensions) that only appears when the app is a Vue app

**Comment by daktwigim** [comment]
I have a same issue.
It worked before, but it is not working since update.

**Comment by willvincent** [comment]
Chrome doesn't seem to persist position of tabs that are not _always_ visible.. Since the vue devtools tab only appears if the current page contains a vue app, its tab position does not persist.

There is a similar issue for the [react extension](https://github.com/facebook/react-devtools/issues/927) that behaves the same way.

Could we not change the behavior of the vue devtools plugin to _always_ be present and simply display some sort of "Vue not present on the current page" message instead of omitting the tab in that case? That should be enough of a change to allow the tab order to persist... and seems like it'd be a pretty easy change to make. I'd submit a PR, but not familiar with chrome plugin dev to know where to look in the code.

**Comment by ortonomy** [comment]
It's been reported as a bug to Chrome team: https://bugs.chromium.org/p/chromium/issues/detail?id=771144 ... no movement on it though...
