### ISSUE TITLE
Devtools change the behavior of source code

### ISSUE THREAD

**Issue by starikan** [vuejs/vue-devtools#456]
I create computed value base on DOM element getBoundingClientRect() data. 

>starPosition: function() {
>    if (this.$refs["icon"]) {
>        let bounds = this.$refs["icon"].getBoundingClientRect();
>        let xy = {
>            x: bounds.x + this.left,
>            y: bounds.y + this.top
>        };
>        console.log(xy)
>        return xy;
>    } else {
>        let xy = {
>            x: 0,
>            y: 0
>        };
>        console.log(xy)
>        return xy;
>    }
>}

console.log(xy) not write any in the console.

But if select root element in devtool it's starting to log data.

If there any watcher on starPosition. I.e. <div>{{starPosition}}</div> or watch: {starPosition: ...} this behavior is not observed.

Source: https://pastebin.com/0jb6GU8N
Video: https://www.youtube.com/watch?v=qJTy8Gt6kN0

**Comment by posva** [comment]
`$refs` are not reactive and on entering the computed property, it skips the code that uses `this.top` and `this.left` and therefore Vue thinks that `starPosition` doesn't have any dependency. You need to make sure Vue can track that dependency `if (this.left || this.top || this.$refs["icon"]) {` should work.
With the devtools opened and the vue instance selected, you probably trigger another call on computed, that's why they appear later
