### ISSUE TITLE
Button to trigger Webpack to recompile

### ISSUE THREAD

**Issue by r7l** [vuejs/vue-devtools#530]
### What problem does this feature solve?
I might be one of a few but i have the problem that webpack-dev-server isn't going to recompile if i change something in my files. My setup is with a dedicated VM with NFS and i've already tried all sorts of options from webpack-dev-server. Currently i have to restart the dev-server allot in order to get it to compile.

It would be an awesome feature to have a button in the extension where you can trigger a recompilation of the code from.

### What does the proposed API look like?
A new Button that says *Compile*.

**Comment by posva** [comment]
Sorry but this is completely unrelated to vue-devtools.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by r7l** [comment]
How is this unrelated? Isn't compilation of code part of development? Isn't this a development tool meant to support developers to write code?

**Comment by r7l** [comment]
Nevermind: Webpack will not help anyways. Just found this: https://github.com/webpack/webpack-dev-server/issues/1250
