### ISSUE TITLE
New blue dark UI colors clash with dark devtools

### ISSUE THREAD

**Issue by controversial** [vuejs/vue-devtools#913]
### Version
5.0.1

### Browser and OS info
Chrome 75 / macOS 10.14.4

### Steps to reproduce
Updating `vue-devtools` to 5.0.1

### What is expected?
The dark vue-devtools would fit with the rest of Chrome’s dark devtools interface

### What is actually happening?
The previous dark theme, which fit with the muted, desaturated dark devtools theme in Chrome, has been replaced with a dark blue theme that clashes with the default dark devtools theme. It seems like the UI colors are coming from [@vuejs/ui](https://github.com/vuejs/ui) and are supposed to be standard across Vue.js projects, but wouldn't it make more sense to make the devtools a “good citizen” of Chrome devtools than to sacrifice that for unity with other Vue.js products?

**Comment by Akryum** [comment]
We're not gonna do specific styling for each version of the devtools.

**Comment by controversial** [comment]
Why was the old styling changed? The chrome dev tools color scheme doesn’t
change; it seems like only Vue-devtools was changed.

**Comment by Akryum** [comment]
I mean Chrome, Firefox and the electron app

**Comment by shealan** [comment]
I know it may seem like a little detail, and even may feel a little nitpicky. However, now Vue Tools doesn't match Chrome's dev tools when it's set to dark mode, or the browser default when the OS is set to dark mode. The dark blue seems out of place and makes the extension feel less integrated into the browser. I would love to see the return of the previously used dark grey - instead of blue so it sits better within Chrome browser, and Electron.

**Comment by Akryum** [comment]
https://github.com/vuejs/ui/issues/28
