### ISSUE TITLE
Dark theme not being saved. Reverts to Light on page reload.

### ISSUE THREAD

**Issue by aeyachts99** [vuejs/vue-devtools#931]
Select dark theme in Settings
Reload page and theme reverts to light.

**Comment by seanmurrin** [comment]
This is likely the same issue I had where settings weren't being stored in localStorage, due to me setting chrome to block 3rd party cookies, which also affects extensions.

I resolved this by adding vue-devtools to the allow list on the chrome cookies setting page (chrome://settings/content/cookies).

`chrome-extension://{vue-devtools extension id}`

Hopefully that helps anyone else in the same boat.

**Comment by aeyachts99** [comment]
I'm not sure I'm entering this correctly. This is what I have which isn't working.
![Screenshot 2019-03-29 at 10 25 05](https://user-images.githubusercontent.com/12847913/55226536-1f053c00-520d-11e9-966d-17750979f6e7.png)

**Comment by seanmurrin** [comment]
> I'm not sure I'm entering this correctly. This is what I have which isn't working.
> ![Screenshot 2019-03-29 at 10 25 05](https://user-images.githubusercontent.com/12847913/55226536-1f053c00-520d-11e9-966d-17750979f6e7.png)

you need to use the extension id (found on extensions settings page - chrome://extensions/). `{vue-devtools extension id}` is just a placeholder for example.

this is what mine looks like - `chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/`

**Comment by aeyachts99** [comment]
Thanks, that sorted it.
