### ISSUE TITLE
devtool doesn't see nested vue instances

### ISSUE THREAD

**Issue by dmitrygorbenko** [vuejs/vue-devtools#984]
### Version
5.1.0

### Browser and OS info
Chrome, Ubuntu 18.04

### Steps to reproduce
Run the following example:
```javascript
<div id="container"></div>
<script>
    let app1 = new Vue({
        data: {
            message: 'Top level instance'
        },
        template: '<div>{{ message }}<div id="nestedContainer"></div></div>'
    });
    app1.$mount();
    document.getElementById("container").appendChild(app1.$el);

    let app2 = new Vue({
        data: {
            message: 'Second level instance'
        },
        template: '<div>{{ message }}</div>'
    });
    app2.$mount();
    document.getElementById("nestedContainer").appendChild(app2.$el);
</script>
```
When open the devtools.

### What is expected?
In the Components tab of the devtools I can see thee Root component  (app1) and the nested component (app2)

### What is actually happening?
In the Components tab of the devtools I can see thee Root component  (app1) and I don't see the nested component (app2)

---
I'm not sure if this case is following the Vue docs, but at least Vue renders this code.

**Comment by Akryum** [comment]
You shouldn't do that, it's bad practice.

**Comment by dmitrygorbenko** [comment]
I want one vue instance (not a component) be inserted into another vue instance (not a component).
Is there some way to do this ?

**Comment by Akryum** [comment]
A Vue instance is the same as a component instance.

**Comment by dmitrygorbenko** [comment]
thanks for helping me !
while I still can't understand how to do what I want, I think it makes sense to close the ticket, right ?

**Comment by Akryum** [comment]
Yes, but keep in mind that everything you do on `new Vue` is the same in a component. Like really the same. Vue does `new Vue` internally to create all the component instances in a Vue "app".

**Comment by it-xtech-dev** [comment]
@Akryum I have real live scenario for nesting vue instance. What conditions should be met for nested vue instance to be revealed inside vue dev tools?

My secnario is:
1. I have a web page which is using third party library that renders charts. 
2. Page contains multiple containers that are filled with charts.
3. Ui, down to container level is controlled by page vue instance.
4. Once containers are rendered by vue page instance, third party lib is used to render charts and mount them inside containers. This lib also uses Vue to render html (below container level).
5. Page level vue instance includes multiple third party library vue instances that are reponsible for managing chart elements.

There is no way to explicitly define chart containers as vue components because their definition is not known for page vue instance.

**Comment by kirkwaiblinger** [comment]
This is still causing an issue for my project as well. I am working on an existing messy webapp that is being converted to Vue incrementally and am unable to access the inner nested components/apps. Is there a known workaround to be able to debug?

**Comment by pawelgur** [comment]
Having same issue in devtools v6.6.4.

In our case we have micro-frontend setup: a host Vue app that contains nested Vue microapp inside its dom tree (mounted on its own, host app ignores this part of dom tree). 
Vue dev tools is not detecting this nested Vue app instance.
Worth noting that when same two Vue apps are mounted to sibling dom nodes (not nested), both are detected by Vue dev tools as expected.

Maybe there's a way to explicitly register nested Vue app instance on vue-dev-tools?
